-- CreateEnum
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'SUPPORT', 'STAFF');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "refreshToken" TEXT,
ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'STAFF',
ALTER COLUMN "createdBy" DROP NOT NULL,
ALTER COLUMN "createdDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "modifiedBy" DROP NOT NULL;
